# Generated by Django 5.2.8 on 2025-11-18 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do ator')),
                ('site', models.URLField(blank=True, verbose_name='Site')),
                ('insta', models.CharField(blank=True, max_length=100, verbose_name='Instagram')),
                ('face', models.CharField(blank=True, max_length=100, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, max_length=100, verbose_name='Twitter')),
                ('nacionalidade', models.CharField(max_length=100, verbose_name='Nacionalidade')),
            ],
            options={
                'verbose_name': 'Ator',
                'verbose_name_plural': 'Atores',
            },
        ),
        migrations.CreateModel(
            name='Continente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do continente')),
            ],
            options={
                'verbose_name': 'Continente',
                'verbose_name_plural': 'Continentes',
            },
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do diretor')),
                ('site', models.URLField(blank=True, verbose_name='Site')),
                ('insta', models.CharField(blank=True, max_length=100, verbose_name='Instagram')),
                ('face', models.CharField(blank=True, max_length=100, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, max_length=100, verbose_name='Twitter')),
                ('nacionalidade', models.CharField(max_length=100, verbose_name='Nacionalidade')),
            ],
            options={
                'verbose_name': 'Diretor',
                'verbose_name_plural': 'Diretores',
            },
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do episódio')),
            ],
            options={
                'verbose_name': 'Episódio',
                'verbose_name_plural': 'Episódios',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do gênero')),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da temporada')),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
            },
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do filme')),
                ('duracao', models.IntegerField(verbose_name='Duração (minutos)')),
                ('sinopse', models.TextField(verbose_name='Sinopse')),
                ('site_oficial', models.URLField(blank=True, verbose_name='Site oficial')),
                ('data_lancamento', models.DateField(verbose_name='Data de lançamento')),
                ('nota_avaliacao', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Nota de avaliação')),
                ('diretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.diretor', verbose_name='Diretor')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.genero', verbose_name='Gênero')),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
            },
        ),
        migrations.CreateModel(
            name='FilmeAtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ator', verbose_name='Ator')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.filme', verbose_name='Filme')),
            ],
            options={
                'verbose_name': 'Filme com Ator',
                'verbose_name_plural': 'Filmes com Atores',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do país')),
                ('continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.continente', verbose_name='Continente')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.AddField(
            model_name='filme',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pais', verbose_name='País'),
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da série')),
                ('duracao', models.IntegerField(verbose_name='Duração média episódio (minutos)')),
                ('sinopse', models.TextField(verbose_name='Sinopse')),
                ('site_oficial', models.URLField(blank=True, verbose_name='Site oficial')),
                ('data_lancamento', models.DateField(verbose_name='Data de lançamento')),
                ('nota_avaliacao', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Nota de avaliação')),
                ('diretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.diretor', verbose_name='Diretor')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.genero', verbose_name='Gênero')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pais', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Série',
                'verbose_name_plural': 'Séries',
            },
        ),
        migrations.CreateModel(
            name='SerieEpisodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracao', models.IntegerField(verbose_name='Duração (minutos)')),
                ('data_disponibilizacao', models.DateField(verbose_name='Data de disponibilização')),
                ('episodio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.episodio', verbose_name='Episódio')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.serie', verbose_name='Série')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.temporada', verbose_name='Temporada')),
            ],
            options={
                'verbose_name': 'Série com Episódio',
                'verbose_name_plural': 'Séries com Episódios',
            },
        ),
    ]
